# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

jobs:
  
  pfml-cal-benefits:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'PFML Benefits Calculator Install Packages'
          command: cd PFML/BenefitsCalculator && npm install
      - run:
          name: 'PFML Benefits Calculator Lint'
          command: cd PFML/BenefitsCalculator && npm run build-css && npm run lint
      - run:
          name: 'PFML Benefits Calculator Build App'
          command: cd PFML/BenefitsCalculator && npm run build
  
  pfml-cal-contribution:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'PFML Contribution Calculator Install Packages'
          command: cd PFML/ContributionCalculator && npm install
      - run:
          name: 'PFML Contribution Calculator Lint'
          command: cd PFML/ContributionCalculator && npm run build-css && npm run lint
      - run:
          name: 'PFML Contribution Calculator Build App'
          command: cd PFML/ContributionCalculator && npm run build
  
  pfml-cal-benefits-deploy-prod:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      # Install AWS cli
      - run: |
          # Only sync to S3 for stable tags.
          if [ "$CIRCLE_BRANCH" == "DP-12695--auto-deploy" ]; then
            sudo apt-get install python-dev python-pip
            sudo pip install awscli
          fi
      - run:
          name: 'PFML Benefits Calculator Install Packages'
          command: cd PFML/BenefitsCalculator && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'PFML Benefits Calculator Deploy Prod App'
          command: |
            if [ "$CIRCLE_BRANCH" == "DP-12695--auto-deploy" ]; then
              cd PFML/BenefitsCalculator && npm run build
              aws s3 sync build s3://calculator.digital.mass.gov/test/pfml/yourbenefits/ --delete
            fi

workflows:
  version: 2
  test:
    jobs:
      - pfml-cal-benefits
      - pfml-cal-contribution
  deploy-prod:
    jobs:
      - pfml-cal-benefits-deploy-prod
          filters:
            branches: { only: /DP-12695--auto-deploy/ }
