# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

jobs:
  # Test jobs for validating calculor code on all branches.
  pfml-cal-benefits-test:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'PFML Benefits Calculator Install Packages'
          command: cd PFML/BenefitsCalculator && npm install
      - run:
          name: 'PFML Benefits Calculator Lint'
          command: cd PFML/BenefitsCalculator && npm run build-css && npm run lint
      - run:
          name: 'PFML Benefits Calculator Build App'
          command: cd PFML/BenefitsCalculator && npm run build
  pfml-cal-contribution-test:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'PFML Contribution Calculator Install Packages'
          command: cd PFML/ContributionCalculator && npm install
      - run:
          name: 'PFML Contribution Calculator Lint'
          command: cd PFML/ContributionCalculator && npm run build-css && npm run lint
      - run:
          name: 'PFML Contribution Calculator Build App'
          command: cd PFML/ContributionCalculator && npm run build
  
  # Deploy develop branches to dev env.
  pfml-cal-benefits-deploy-dev:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "PFML/BenefitsCalculator/package.json" }}
      - run: 
          name: 'Install awscli'
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              sudo apt-get install python-dev python-pip
              sudo pip install awscli
            fi
      - run:
          name: 'PFML Benefits Calculator Install Packages'
          command: cd PFML/BenefitsCalculator && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "PFML/BenefitsCalculator/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'PFML Benefits Calculator Deploy Dev App'
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              cd PFML/BenefitsCalculator && npm run build:development
              aws s3 sync build s3://calculator.digital.mass.gov/dev/pfml/yourbenefits/ --delete
            fi
  pfml-cal-contribution-deploy-dev:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "PFML/ContributionCalculator/package.json" }}
      - run: 
          name: 'Install awscli'
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              sudo apt-get install python-dev python-pip
              sudo pip install awscli
            fi
      - run:
          name: 'PFML Contribution Calculator Install Packages'
          command: cd PFML/ContributionCalculator && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "PFML/ContributionCalculator/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'PFML Contribution Calculator Deploy Dev App'
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              cd PFML/ContributionCalculator && npm run build:development
              aws s3 sync build s3://calculator.digital.mass.gov/dev/pfml/contribution/ --delete
            fi
  ui-cal-benefits-deploy-dev:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "UI/BenefitsCalculator/package.json" }}
      - run: 
          name: 'Install awscli'
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              sudo apt-get install python-dev python-pip
              sudo pip install awscli
            fi
      - run:
          name: 'UI Benefits Calculator Install Packages'
          command: cd UI/BenefitsCalculator/ && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "UI/BenefitsCalculator/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'UI Benefits Calculator Deploy Dev App'
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              cd UI/BenefitsCalculator/ && npm run build:development
              aws s3 sync build s3://calculator.digital.mass.gov/dev/ui/yourbenefits/ --delete
            fi
  ui-cal-parttime-deploy-dev:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "UI/PartTimeBenefitsCalculator/package.json" }}
      - run: 
          name: 'Install awscli'
          command: |
            if [ "$CIRCLE_BRANCH" == "DP-12695--auto-deploy" ]; then
              sudo apt-get install python-dev python-pip
              sudo pip install awscli
            fi
      - run:
          name: 'UI Part Time Benefits Calculator Install Packages'
          command: cd UI/PartTimeBenefitsCalculator && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "UI/PartTimeBenefitsCalculator/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'UI Part Time Benefits Calculator Deploy Dev App'
          command: |
            if [ "$CIRCLE_BRANCH" == "DP-12695--auto-deploy" ]; then
              cd UI/PartTimeBenefitsCalculator && npm run build:development
              aws s3 sync build s3://calculator.digital.mass.gov/dev/ui/parttimebenefits/ --delete
            fi

  # Deploy master branches to production ev.
  pfml-cal-benefits-deploy-prod:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "PFML/BenefitsCalculator/package.json" }}
      - run: 
          name: 'Install awscli'
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              sudo apt-get install python-dev python-pip
              sudo pip install awscli
            fi
      - run:
          name: 'PFML Benefits Calculator Install Packages'
          command: cd PFML/BenefitsCalculator && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "PFML/BenefitsCalculator/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'PFML Benefits Calculator Deploy Prod App'
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              cd PFML/BenefitsCalculator && npm run build
              aws s3 sync build s3://calculator.digital.mass.gov/pfml/yourbenefits/ --delete
            fi
  pfml-cal-contribution-deploy-prod:
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "PFML/ContributionCalculator/package.json" }}
      - run: 
          name: 'Install awscli'
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              sudo apt-get install python-dev python-pip
              sudo pip install awscli
            fi
      - run:
          name: 'PFML Contribution Calculator Install Packages'
          command: cd PFML/ContributionCalculator && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "PFML/ContributionCalculator/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'PFML Contribution Calculator Deploy Prod App'
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              cd PFML/ContributionCalculator && npm run build
              aws s3 sync build s3://calculator.digital.mass.gov/pfml/contribution/ --delete
            fi

workflows:
  version: 2
  test:
    jobs:
      - pfml-cal-benefits-test
      - pfml-cal-contribution-test
  deploy-dev:
    jobs:
      - pfml-cal-benefits-deploy-dev:
          filters:
            branches: { only: develop }
      - pfml-cal-contribution-deploy-dev:
          filters:
            branches: { only: develop }
      - ui-cal-benefits-deploy-dev:
          filters:
            branches: { only: develop }
      - ui-cal-parttime-deploy-dev:
          filters:
            branches: { only: DP-12695--auto-deploy }
  deploy-prod:
    jobs:
      - pfml-cal-benefits-deploy-prod:
          filters:
            branches: { only: master }
      - pfml-cal-contribution-deploy-prod:
          filters:
            branches: { only: master }
      
